apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: event-system
type: Opaque
stringData:
  password: "1234"
  user: "user"
  db_dsn: "host=postgres user=user password=1234 dbname=event port=5432 sslmode=disable TimeZone=Asia/Seoul"

---

apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: event-system
type: Opaque
stringData:
  admin_password: "1234"
