apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres_event_db
    url: postgres:5432
    database: event
    user: user
    secureJsonData:
      password: "1234"
    jsonData:
      sslmode: "disable" # 로컬/테스트 환경용
      postgresVersion: 1500 # PostgreSQL 버전 (15.x 기준)
      timescaledb: false
    isDefault: true
    editable: true
