{
 "title": "데이터 집계 분석",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "메타데이터 내 특정 에러별 집계",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "event",
     "rawSql": "SELECT \n  metadata->>'code' as ErrorResponse,\n  CASE \n    WHEN (metadata->>'code')::int BETWEEN 400 AND 499 THEN '4xx'\n    WHEN (metadata->>'code')::int BETWEEN 500 AND 599 THEN '5xx'\n    ELSE 'Etc'\n  END as ErrorType,\n  count(*) as Count\nFROM events\nWHERE event_type = 'error' AND $__timeFilter(created_at)\nGROUP BY 1, 2\nORDER BY Count;"
    }
   ]
  },
  {
   "title": "에러 이벤트 비율",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "event",
     "rawSql": "SELECT \n  (COUNT(*) FILTER (WHERE event_type = 'error')::float / \n   NULLIF(COUNT(*), 0)::float) * 100 as error_rate\nFROM events\nWHERE $__timeFilter(created_at);"
    }
   ]
  },
  {
   "title": "유저별 총 이벤트 수",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "dataset": "event",
     "rawSql": "SELECT \n  user_id, \n  COUNT(*) FILTER (WHERE event_type = 'purchase') as purchase_count,\n  COUNT(*) FILTER (WHERE event_type = 'refund') as refund_count,\n  COUNT(*) FILTER (WHERE event_type IN ('purchase', 'refund')) as total_activity\nFROM events\nWHERE $__timeFilter(created_at)\nGROUP BY user_id\nORDER BY total_activity DESC\nLIMIT 15;"
    }
   ]
  },
  {
   "title": "시간대별 이벤트 추이",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "event",
     "rawSql": "SELECT \n $__timeGroupAlias(created_at, $__interval), \n event_type AS metric, \n count(*) AS count \n FROM events \n WHERE \n $__timeFilter(created_at) AND \n event_type IN ('page_view', 'purchase', 'refund', 'error') \n GROUP BY 1, 2 \n ORDER BY 1;"
    }
   ]
  },
  {
   "title": "이벤트 타입별 발생 횟수",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "dataset": "event",
     "rawSql": "SELECT \n  event_type, \n  count(*) as count\nFROM events\nWHERE $__timeFilter(created_at)\nGROUP BY event_type\nORDER BY count DESC;"
    }
   ]
  }
 ]
}